server:
  port: "8085"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  shutdown_timeout: 10s

crawler:
  maxDepth: 3
  userAgent: "synx-crawler/1.0"
  async: false
  timeout: 30s
  num_workers: 5

checkpoint:
  enabled: true
  type: file
  filePath: "/var/lib/synx/checkpoint.json"

logging:
  level: "info"
  output: "/var/log/synx/synx.log"

headers:
  User-Agent: "synx-crawler/1.0"
  Accept: "application/json"
  Accept-Language: "en-US,en;q=0.9"

storage:
  elasticsearch:
    endpoint: "http://elasticsearch:9200"
    index: "synx-doc"
    timeout: 10s
    retryLimit: 3

redis:
  endpoint: "redis:6379"
  db: 0
  password: ""
  queueKey: "synx-queue"
  visitedKey: "synx-visited"
  retryLimit: 3

metrics:
  host: "0.0.0.0"
  port: 9100
